import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return <>
    <div className={styles.container}>
      <style jsx>
        {`
      h2{
        font-size:38px;
      }
      h3{
        font-size:28px;

        margin-bottom:2rem;
      }
      .blogs{
        padding-bottom:3rem;
      }
    `}
      </style>
      <Head>
        <title >Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, hunting coder, hunting blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan dummy">Hunting Coder</span>
        </h1>
        <div className={styles.imgWrap}>

          <Image className={styles.myImg} src='/coder.jpg' alt='coder' width={518} height={345} priority={true} />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2 className={styles.secondaryHeading}>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
          </div>
        </div>
      </main>


    </div>
  </>;
}
