import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return <>
    <div className={styles.container}>
      {/* <style jsx>
        {`
      h2{
        font-size:38px;
      }
      h3{
        font-size:28px;

        margin-bottom:2rem;
      }
      .blogs{
        padding-bottom:3rem;
      }
    `} 
      </style>
    */}
      <Head>
        <title >Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, hunting coder, hunting blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.imgWrap}>

          <Image className={styles.myImg} src='/coder.jpg' alt='coder' width={199} height={199} priority={true} />
        </div>
        <h1 className={styles.title}>
          <span className="mySpan dummy"> &lt;HuntingCoder/&gt;</span>
        </h1>


        <div className="blogs">
          <h2 className={styles.secondaryHeading}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
            <button className={styles.btn} type="submit">Read more</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
            <button className={styles.btn} type="submit">Read more</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn javascript </h3>
            <p>javascript is the languauge to design logic on web</p>
            <button className={styles.btn} type="submit">Read more</button>
          </div>
        </div>
      </main>


    </div>
  </>;
}
